<?php

namespace AppBundle\Repository;

/**
 * CategorieChaineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorieChaineRepository extends \Doctrine\ORM\EntityRepository
{
}
