<?php

namespace AppBundle\Repository;

/**
 * NiveauChaineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NiveauChaineRepository extends \Doctrine\ORM\EntityRepository
{
}
